# [[faucets]]
# symbol = "BTC"
# decimals = 8
# max_supply = 1_000_000_000_000_000_000

[[faucets]]
symbol = "SPWN"
decimals = 8
max_supply = 1_000_000_000_000_000_000

[[faucets]]
symbol = "REGY"
decimals = 8
max_supply = 1_000_000_000_000_000_000
